In [ ]:
#create a table for the 2 basketball Bundesliga
#we need: season,  rank, teamname, games played, wins , losses, points, pts + , pts -, point difference.(columns)
#list[]
#rows = teams 
#rank 1-n dynamic, function depending on points and , direct comparison(punktegleichheit)and point difference
# unique teamnames
# games played: for loop , everytime a result happens the games played increases by 1. count + 1
# wins : count for loop , if teams score higher then opponent score
#losses: same else statement
# pts +:adding one scores for loop
#pts - : adding opponent scores for loop
# difference:  for loop (pts + - pts-)

In [1]:
import time
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import csv

In [3]:
table = pd.read_csv("data/2021_22_matches.csv", sep=",")
table.tail()

,id,season,matchday,date,time,home,guest,result,link
326,108859,2021_22,Spieltag 34,09.04.2022,19:30,TEAM EHINGEN URSPRING,RÖMERSTROM Gladiators Trier,69:101,http://live.2basketballbundesliga.de/g/108859?...
327,108855,2021_22,Spieltag 34,09.04.2022,19:30,Medipolis SC Jena,VfL SparkassenStars Bochum,121:83,http://live.2basketballbundesliga.de/g/108855?...
328,108860,2021_22,Spieltag 34,09.04.2022,19:30,VfL Kirchheim Knights,Nürnberg Falcons BC,57:89,http://live.2basketballbundesliga.de/g/108860?...
329,108857,2021_22,Spieltag 34,09.04.2022,19:30,Itzehoe Eagles,RASTA Vechta,67:84,http://live.2basketballbundesliga.de/g/108857?...
330,108854,2021_22,Spieltag 34,19.04.2022,18:00,ROSTOCK SEAWOLVES,PS Karlsruhe LIONS,73:80,http://live.2basketballbundesliga.de/g/108854?...

In [12]:
table['matchday'] = table['matchday'].str.replace("Spieltag ","")

In [15]:
table.head()

,id,season,matchday,date,time,home,guest,result,link
0,108931,2021_22,PO-1/4 Finale Spiel 1,14.04.2022,19:30,Tigers Tübingen,Eisbären Bremerhaven,82:78,http://live.2basketballbundesliga.de/g/108931?...
1,108930,2021_22,PO-1/4 Finale Spiel 1,22.04.2022,19:30,RÖMERSTROM Gladiators Trier,Bayer Giants Leverkusen,92:68,http://live.2basketballbundesliga.de/g/108930?...
2,108933,2021_22,PO-1/4 Finale Spiel 1,22.04.2022,19:30,Medipolis SC Jena,Uni Baskets Paderborn,89:84,http://live.2basketballbundesliga.de/g/108933?...
3,108932,2021_22,PO-1/4 Finale Spiel 1,26.04.2022,19:30,ROSTOCK SEAWOLVES,PS Karlsruhe LIONS,107:103,http://live.2basketballbundesliga.de/g/108932?...
4,108936,2021_22,PO-1/4 Finale Spiel 2,17.04.2022,18:00,Eisbären Bremerhaven,Tigers Tübingen,75:82,http://live.2basketballbundesliga.de/g/108936?...

In [14]:
table.dtypes

id           int64
season      object
matchday    object
date        object
time        object
home        object
guest       object
result      object
link        object
dtype: object

In [28]:
table1 = table[table['matchday'].map(len) < 3]
table1.head()

,id,season,matchday,date,time,home,guest,result,link
25,108961,2021_22,1,N.N.,NaN,spielfrei,Itzehoe Eagles,--:--,http://live.2basketballbundesliga.de/g/108961?...
26,108556,2021_22,1,17.09.2021,19:30,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,http://live.2basketballbundesliga.de/g/108556?...
27,108557,2021_22,1,18.09.2021,18:30,Nürnberg Falcons BC,Artland Dragons,74:71,http://live.2basketballbundesliga.de/g/108557?...
28,108558,2021_22,1,18.09.2021,19:00,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,http://live.2basketballbundesliga.de/g/108558?...
29,108559,2021_22,1,18.09.2021,19:00,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,http://live.2basketballbundesliga.de/g/108559?...

In [30]:
table1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306 entries, 25 to 330
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        306 non-null    int64
 1   season    306 non-null    object
 2   matchday  306 non-null    object
 3   date      306 non-null    object
 4   time      272 non-null    object
 5   home      306 non-null    object
 6   guest     306 non-null    object
 7   result    306 non-null    object
 8   link      306 non-null    object
dtypes: int64(1), object(8)
memory usage: 23.9+ KB

In [34]:
table1 = table1.drop(['link', 'id', 'time', 'date'], axis=1)
table1.head()

,season,matchday,home,guest,result
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87

In [36]:
table1[['pts+', 'pts-']] = table1.result.str.split(":", expand=True)
table1.head()

,season,matchday,home,guest,result,pts+,pts-
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--,--,--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87

In [40]:
table1 = table1.drop(table1.index[table1['guest'] == 'spielfrei'])
table1.head()

,season,matchday,home,guest,result,pts+,pts-
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--,--,--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87

In [41]:
table1 = table1.drop(table1.index[table1['home'] == 'spielfrei'])
table1.head()

,season,matchday,home,guest,result,pts+,pts-
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87
30,2021_22,1,wiha Panthers Schwenningen,Phoenix Hagen,63:78,63,78

In [42]:
display(table1.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 272 entries, 26 to 330
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   season    272 non-null    object
 1   matchday  272 non-null    object
 2   home      272 non-null    object
 3   guest     272 non-null    object
 4   result    272 non-null    object
 5   pts+      272 non-null    object
 6   pts-      272 non-null    object
dtypes: object(7)
memory usage: 17.0+ KB

None

In [43]:
table1.head()

,season,matchday,home,guest,result,pts+,pts-
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87
30,2021_22,1,wiha Panthers Schwenningen,Phoenix Hagen,63:78,63,78

In [45]:
tabelle = ['season', 'rank', 'team', 'games_played', 'wins', 'losses', 'points', 'pts+', 'pts-', 'point_difference' ]

In [47]:
df = pd.DataFrame(columns=tabelle)
df.head()

Empty DataFrame
Columns: [season, rank, team, games_played, wins, losses, points, pts+, pts-, point_difference]
Index: []