In [ ]:
#create a table for the 2 basketball Bundesliga
#we need: season,  rank, teamname, games played, wins , losses, points, pts + , pts -, point difference.(columns)
#list[]
#rows = teams 
#rank 1-n dynamic, function depending on points and , direct comparison(punktegleichheit)and point difference
# unique teamnames
# games played: for loop , everytime a result happens the games played increases by 1. count + 1
# wins : count for loop , if teams score higher then opponent score
#losses: same else statement
# pts +:adding one scores for loop
#pts - : adding opponent scores for loop
# difference:  for loop (pts + - pts-)

In [208]:
import time
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import csv

In [209]:
table = pd.read_csv("data/2021_22_matches.csv", sep=",")
table.tail()

,id,season,matchday,date,time,home,guest,result,link
326,108859,2021_22,Spieltag 34,09.04.2022,19:30,TEAM EHINGEN URSPRING,RÖMERSTROM Gladiators Trier,69:101,http://live.2basketballbundesliga.de/g/108859?...
327,108855,2021_22,Spieltag 34,09.04.2022,19:30,Medipolis SC Jena,VfL SparkassenStars Bochum,121:83,http://live.2basketballbundesliga.de/g/108855?...
328,108860,2021_22,Spieltag 34,09.04.2022,19:30,VfL Kirchheim Knights,Nürnberg Falcons BC,57:89,http://live.2basketballbundesliga.de/g/108860?...
329,108857,2021_22,Spieltag 34,09.04.2022,19:30,Itzehoe Eagles,RASTA Vechta,67:84,http://live.2basketballbundesliga.de/g/108857?...
330,108854,2021_22,Spieltag 34,19.04.2022,18:00,ROSTOCK SEAWOLVES,PS Karlsruhe LIONS,73:80,http://live.2basketballbundesliga.de/g/108854?...

In [210]:
table['matchday'] = table['matchday'].str.replace("Spieltag ","")

In [ ]:
table.head()

In [ ]:
table.dtypes

In [211]:
table1 = table[table['matchday'].map(len) < 3]
table1.head()

,id,season,matchday,date,time,home,guest,result,link
25,108961,2021_22,1,N.N.,NaN,spielfrei,Itzehoe Eagles,--:--,http://live.2basketballbundesliga.de/g/108961?...
26,108556,2021_22,1,17.09.2021,19:30,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,http://live.2basketballbundesliga.de/g/108556?...
27,108557,2021_22,1,18.09.2021,18:30,Nürnberg Falcons BC,Artland Dragons,74:71,http://live.2basketballbundesliga.de/g/108557?...
28,108558,2021_22,1,18.09.2021,19:00,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,http://live.2basketballbundesliga.de/g/108558?...
29,108559,2021_22,1,18.09.2021,19:00,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,http://live.2basketballbundesliga.de/g/108559?...

In [ ]:
table1.info()

In [212]:
table1 = table1.drop(['link', 'id', 'time', 'date'], axis=1)
table1.head()

,season,matchday,home,guest,result
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87

In [213]:
table1[['pts+', 'pts-']] = table1.result.str.split(":", expand=True)
table1.head()

,season,matchday,home,guest,result,pts+,pts-
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--,--,--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87

In [214]:
table1 = table1.drop(table1.index[table1['guest'] == 'spielfrei'])
table1.head()

,season,matchday,home,guest,result,pts+,pts-
25,2021_22,1,spielfrei,Itzehoe Eagles,--:--,--,--
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87

In [215]:
table1 = table1.drop(table1.index[table1['home'] == 'spielfrei'])
table1.head()

,season,matchday,home,guest,result,pts+,pts-
26,2021_22,1,RASTA Vechta,ROSTOCK SEAWOLVES,54:68,54,68
27,2021_22,1,Nürnberg Falcons BC,Artland Dragons,74:71,74,71
28,2021_22,1,VfL SparkassenStars Bochum,Medipolis SC Jena,74:91,74,91
29,2021_22,1,Eisbären Bremerhaven,RÖMERSTROM Gladiators Trier,84:87,84,87
30,2021_22,1,wiha Panthers Schwenningen,Phoenix Hagen,63:78,63,78

In [ ]:
display(table1.info())

In [ ]:
table1.head()

In [216]:
table1['pts+'] = table1['pts+'].astype(int)

In [217]:
table1['pts-'] = table1['pts-'].astype(int)

In [218]:
tabelle = ['season', 'rank', 'team', 'games_played', 'wins', 'losses', 'points', 'pts_plus', 'pts_minus', 'point_difference' ]

In [219]:
df = pd.DataFrame(columns=tabelle)
df.head()

Empty DataFrame
Columns: [season, rank, team, games_played, wins, losses, points, pts_plus, pts_minus, point_difference]
Index: []

In [ ]:
season = []
rank = []
team = []
games_played = []
wins = []
losses = []
points = []
pts_plus = []
pts_minus = []
points_difference = []

In [ ]:
for i in table1['home']:
  
    rank = [0]
    games_played = [0]
    wins = [0]
    losses = [0]
    points = [0]
    pts_plus = [0]
    pts_minus = [0]
    points_difference = [0]

In [220]:
teams = table1['guest'].unique()
display(teams)

array(['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena',
       'RÖMERSTROM Gladiators Trier', 'Phoenix Hagen', 'Tigers Tübingen',
       'TEAM EHINGEN URSPRING    ', 'PS Karlsruhe LIONS',
       'Itzehoe Eagles', 'Nürnberg Falcons BC', 'Eisbären Bremerhaven',
       'Uni Baskets Paderborn', 'VfL Kirchheim Knights', 'RASTA Vechta',
       'Bayer Giants Leverkusen', 'wiha Panthers Schwenningen',
       'VfL SparkassenStars Bochum'], dtype=object)

In [ ]:
set_teams = set(teams)
print(set_teams)

In [ ]:
matchday_1 = table1.query('matchday == "1"')
matchday_1

In [ ]:
liste_home = []
for x in matchday_1['home']:
    liste_home.append(x)

    print(liste_home)

In [224]:
set_home = set(liste_home)
print(set_home)

{'wiha Panthers Schwenningen', 'Uni Baskets Paderborn', 'VfL SparkassenStars Bochum', 'Eisbären Bremerhaven', 'VfL Kirchheim Knights', 'Bayer Giants Leverkusen', 'Nürnberg Falcons BC', 'RASTA Vechta'}

In [225]:
for x in matchday_1['guest']:
    print(x)

ROSTOCK SEAWOLVES
Artland Dragons
Medipolis SC Jena
RÖMERSTROM Gladiators Trier
Phoenix Hagen
Tigers Tübingen
TEAM EHINGEN URSPRING
PS Karlsruhe LIONS

In [226]:
liste_guest = []
for x in matchday_1['guest']:
    liste_guest.append(x)

    print(liste_guest)

['ROSTOCK SEAWOLVES']
['ROSTOCK SEAWOLVES', 'Artland Dragons']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena', 'RÖMERSTROM Gladiators Trier']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena', 'RÖMERSTROM Gladiators Trier', 'Phoenix Hagen']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena', 'RÖMERSTROM Gladiators Trier', 'Phoenix Hagen', 'Tigers Tübingen']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena', 'RÖMERSTROM Gladiators Trier', 'Phoenix Hagen', 'Tigers Tübingen', 'TEAM EHINGEN URSPRING    ']
['ROSTOCK SEAWOLVES', 'Artland Dragons', 'Medipolis SC Jena', 'RÖMERSTROM Gladiators Trier', 'Phoenix Hagen', 'Tigers Tübingen', 'TEAM EHINGEN URSPRING    ', 'PS Karlsruhe LIONS']

In [227]:

liste_home = []
for x in matchday_1['home']:
    liste_home.append(x)

liste_guest = []
for x in matchday_1['guest']:
    liste_guest.append(x)




set_guest = set(liste_guest)
set_home = set(liste_home)
set_spielfrei = set_teams.symmetric_difference(set_home)
set_spielfrei_final = set_spielfrei.symmetric_difference(set_guest)
spielfrei = list(set_spielfrei_final)

set

In [228]:
# set_spielfrei = Set_teams - set_home - set_guest

set_spielfrei = set_teams.symmetric_difference(set_home)

{'Artland Dragons', 'RÖMERSTROM Gladiators Trier', 'Itzehoe Eagles', 'PS Karlsruhe LIONS', 'Medipolis SC Jena', 'TEAM EHINGEN URSPRING    ', 'Tigers Tübingen', 'Phoenix Hagen', 'ROSTOCK SEAWOLVES'}

In [234]:
set_spielfrei_final = set_spielfrei.symmetric_difference(set_guest)
spielfrei = list(set_spielfrei_final)
print(spielfrei)

['Itzehoe Eagles']

In [ ]:
matchday_1.info()

In [230]:
df.head()

Empty DataFrame
Columns: [season, rank, team, games_played, wins, losses, points, pts_plus, pts_minus, point_difference]
Index: []

In [231]:
for index, row in matchday_1.iterrows():
    if row['pts+'] > row['pts-']:
        df.loc[df.shape[0]]= ['2021_22', 0 , row['home'] , 1 , 1 , 0 , 2 , row['pts+'] , row['pts-'] , (row['pts+'] - row['pts-'])]
        df.loc[df.shape[0]] = ['2021_22', 0 , row['guest'] , 1 , 0 , 1 , 0 , row['pts-'] , row['pts+'] , (row['pts-'] - row['pts+'])]
        
    else:
        df.loc[df.shape[0]] = ['2021_22', 0 , row['home'] , 1 , 0 , 1 , 0 , row['pts+'] , row['pts-'] , (row['pts+'] - row['pts-'])]
        df.loc[df.shape[0]]= ['2021_22', 0 , row['guest'] , 1 , 1 , 0 , 2 , row['pts-'] , row['pts+'] , (row['pts-'] - row['pts+'])]

   
df

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
0,2021_22,0,RASTA Vechta,1,0,1,0,54,68,-14
1,2021_22,0,ROSTOCK SEAWOLVES,1,1,0,2,68,54,14
2,2021_22,0,Nürnberg Falcons BC,1,1,0,2,74,71,3
3,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
4,2021_22,0,VfL SparkassenStars Bochum,1,0,1,0,74,91,-17
5,2021_22,0,Medipolis SC Jena,1,1,0,2,91,74,17
6,2021_22,0,Eisbären Bremerhaven,1,0,1,0,84,87,-3
7,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,87,84,3
8,2021_22,0,wiha Panthers Schwenningen,1,0,1,0,63,78,-15
9,2021_22,0,Phoenix Hagen,1,1,0,2,78,63,15
10,2021_22,0,VfL Kirchheim Knights,1,0,1,0,67,83,-16
11,2021_22,0,Tigers Tübingen,1,1,0,2,83,67,16
12,2021_22,0,Uni Baskets Paderborn,1,1,0,2,98,81,17
13,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,81,98,-17
14,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,109,71,38
15,2021_22,0,PS Karlsruhe LIONS,1,0,1,0,71,109,-38

In [242]:
df.loc[df.shape[0]] = ['2021_22', 0 , spielfrei[0] , 0 , 0 , 0 , 0 , 0 , 0 , 0]

In [246]:
df.drop([17,18], axis=0, inplace=True)

In [247]:
df

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
0,2021_22,0,RASTA Vechta,1,0,1,0,54,68,-14
1,2021_22,0,ROSTOCK SEAWOLVES,1,1,0,2,68,54,14
2,2021_22,0,Nürnberg Falcons BC,1,1,0,2,74,71,3
3,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
4,2021_22,0,VfL SparkassenStars Bochum,1,0,1,0,74,91,-17
5,2021_22,0,Medipolis SC Jena,1,1,0,2,91,74,17
6,2021_22,0,Eisbären Bremerhaven,1,0,1,0,84,87,-3
7,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,87,84,3
8,2021_22,0,wiha Panthers Schwenningen,1,0,1,0,63,78,-15
9,2021_22,0,Phoenix Hagen,1,1,0,2,78,63,15
10,2021_22,0,VfL Kirchheim Knights,1,0,1,0,67,83,-16
11,2021_22,0,Tigers Tübingen,1,1,0,2,83,67,16
12,2021_22,0,Uni Baskets Paderborn,1,1,0,2,98,81,17
13,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,81,98,-17
14,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,109,71,38
15,2021_22,0,PS Karlsruhe LIONS,1,0,1,0,71,109,-38
20,2021_22,0,Itzehoe Eagles,0,0,0,0,0,0,0

In [253]:
df.sort_values(['points', 'point_difference', 'pts_plus'], ascending=False)

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
14,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,109,71,38
12,2021_22,0,Uni Baskets Paderborn,1,1,0,2,98,81,17
5,2021_22,0,Medipolis SC Jena,1,1,0,2,91,74,17
11,2021_22,0,Tigers Tübingen,1,1,0,2,83,67,16
9,2021_22,0,Phoenix Hagen,1,1,0,2,78,63,15
1,2021_22,0,ROSTOCK SEAWOLVES,1,1,0,2,68,54,14
7,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,87,84,3
2,2021_22,0,Nürnberg Falcons BC,1,1,0,2,74,71,3
20,2021_22,0,Itzehoe Eagles,0,0,0,0,0,0,0
6,2021_22,0,Eisbären Bremerhaven,1,0,1,0,84,87,-3
3,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
0,2021_22,0,RASTA Vechta,1,0,1,0,54,68,-14
8,2021_22,0,wiha Panthers Schwenningen,1,0,1,0,63,78,-15
10,2021_22,0,VfL Kirchheim Knights,1,0,1,0,67,83,-16
13,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,81,98,-17
4,2021_22,0,VfL SparkassenStars Bochum,1,0,1,0,74,91,-17
15,2021_22,0,PS Karlsruhe LIONS,1,0,1,0,71,109,-38

In [255]:
df1 = df.sort_values(['points', 'point_difference', 'pts_plus'], ascending=False)
df1

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
14,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,109,71,38
12,2021_22,0,Uni Baskets Paderborn,1,1,0,2,98,81,17
5,2021_22,0,Medipolis SC Jena,1,1,0,2,91,74,17
11,2021_22,0,Tigers Tübingen,1,1,0,2,83,67,16
9,2021_22,0,Phoenix Hagen,1,1,0,2,78,63,15
1,2021_22,0,ROSTOCK SEAWOLVES,1,1,0,2,68,54,14
7,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,87,84,3
2,2021_22,0,Nürnberg Falcons BC,1,1,0,2,74,71,3
20,2021_22,0,Itzehoe Eagles,0,0,0,0,0,0,0
6,2021_22,0,Eisbären Bremerhaven,1,0,1,0,84,87,-3
3,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
0,2021_22,0,RASTA Vechta,1,0,1,0,54,68,-14
8,2021_22,0,wiha Panthers Schwenningen,1,0,1,0,63,78,-15
10,2021_22,0,VfL Kirchheim Knights,1,0,1,0,67,83,-16
13,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,81,98,-17
4,2021_22,0,VfL SparkassenStars Bochum,1,0,1,0,74,91,-17
15,2021_22,0,PS Karlsruhe LIONS,1,0,1,0,71,109,-38

In [257]:
df2 = pd.DataFrame(columns=tabelle)
df2

Empty DataFrame
Columns: [season, rank, team, games_played, wins, losses, points, pts_plus, pts_minus, point_difference]
Index: []

In [258]:
matchday_2 = table1.query('matchday == "2"')

In [259]:

liste_home2 = []
for x in matchday_2['home']:
    liste_home2.append(x)

liste_guest2 = []
for x in matchday_2['guest']:
    liste_guest2.append(x)



set_teams = set(teams)
set_guest2 = set(liste_guest2)
set_home2 = set(liste_home2)
set_spielfrei2 = set_teams.symmetric_difference(set_home2)
set_spielfrei_final2 = set_spielfrei2.symmetric_difference(set_guest2)
spielfrei2 = list(set_spielfrei_final2)

spielfrei2

['Artland Dragons']

In [260]:
for index, row in matchday_2.iterrows():
    if row['pts+'] > row['pts-']:
        df2.loc[df2.shape[0]]= ['2021_22', 0 , row['home'] , 1 , 1 , 0 , 2 , row['pts+'] , row['pts-'] , (row['pts+'] - row['pts-'])]
        df2.loc[df2.shape[0]] = ['2021_22', 0 , row['guest'] , 1 , 0 , 1 , 0 , row['pts-'] , row['pts+'] , (row['pts-'] - row['pts+'])]
        
    else:
        df2.loc[df2.shape[0]] = ['2021_22', 0 , row['home'] , 1 , 0 , 1 , 0 , row['pts+'] , row['pts-'] , (row['pts+'] - row['pts-'])]
        df2.loc[df2.shape[0]]= ['2021_22', 0 , row['guest'] , 1 , 1 , 0 , 2 , row['pts-'] , row['pts+'] , (row['pts-'] - row['pts+'])]

df2.loc[df2.shape[0]] = ['2021_22', 0 , spielfrei2[0] , 0 , 0 , 0 , 0 , 0 , 0 , 0]

df2.sort_values(['points', 'point_difference', 'pts_plus'], ascending=False)

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
12,2021_22,0,PS Karlsruhe LIONS,1,1,0,2,97,70,27
14,2021_22,0,Phoenix Hagen,1,1,0,2,83,57,26
6,2021_22,0,Medipolis SC Jena,1,1,0,2,88,71,17
5,2021_22,0,Itzehoe Eagles,1,1,0,2,94,78,16
10,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,89,75,14
2,2021_22,0,VfL SparkassenStars Bochum,1,1,0,2,77,65,12
0,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,95,85,10
8,2021_22,0,wiha Panthers Schwenningen,1,1,0,2,83,81,2
16,2021_22,0,Artland Dragons,0,0,0,0,0,0,0
9,2021_22,0,Eisbären Bremerhaven,1,0,1,0,81,83,-2
1,2021_22,0,ROSTOCK SEAWOLVES,1,0,1,0,85,95,-10
3,2021_22,0,Tigers Tübingen,1,0,1,0,65,77,-12
11,2021_22,0,Uni Baskets Paderborn,1,0,1,0,75,89,-14
4,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,78,94,-16
7,2021_22,0,Nürnberg Falcons BC,1,0,1,0,71,88,-17
15,2021_22,0,RASTA Vechta,1,0,1,0,57,83,-26
13,2021_22,0,VfL Kirchheim Knights,1,0,1,0,70,97,-27

In [273]:
df_sort2 = df2.sort_values('team')

df_sort2 = df_sort2.reset_index()

df_sort2 = df_sort2.drop('index', axis=1)

df_sort2

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
0,2021_22,0,Artland Dragons,0,0,0,0,0,0,0
1,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,95,85,10
2,2021_22,0,Eisbären Bremerhaven,1,0,1,0,81,83,-2
3,2021_22,0,Itzehoe Eagles,1,1,0,2,94,78,16
4,2021_22,0,Medipolis SC Jena,1,1,0,2,88,71,17
5,2021_22,0,Nürnberg Falcons BC,1,0,1,0,71,88,-17
6,2021_22,0,PS Karlsruhe LIONS,1,1,0,2,97,70,27
7,2021_22,0,Phoenix Hagen,1,1,0,2,83,57,26
8,2021_22,0,RASTA Vechta,1,0,1,0,57,83,-26
9,2021_22,0,ROSTOCK SEAWOLVES,1,0,1,0,85,95,-10
10,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,89,75,14
11,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,78,94,-16
12,2021_22,0,Tigers Tübingen,1,0,1,0,65,77,-12
13,2021_22,0,Uni Baskets Paderborn,1,0,1,0,75,89,-14
14,2021_22,0,VfL Kirchheim Knights,1,0,1,0,70,97,-27
15,2021_22,0,VfL SparkassenStars Bochum,1,1,0,2,77,65,12
16,2021_22,0,wiha Panthers Schwenningen,1,1,0,2,83,81,2

In [274]:
df_sort1 = df1.sort_values('team')

df_sort1 = df_sort1.reset_index()

df_sort1 = df_sort1.drop('index', axis=1)

df_sort1

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
0,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
1,2021_22,0,Bayer Giants Leverkusen,1,1,0,2,109,71,38
2,2021_22,0,Eisbären Bremerhaven,1,0,1,0,84,87,-3
3,2021_22,0,Itzehoe Eagles,0,0,0,0,0,0,0
4,2021_22,0,Medipolis SC Jena,1,1,0,2,91,74,17
5,2021_22,0,Nürnberg Falcons BC,1,1,0,2,74,71,3
6,2021_22,0,PS Karlsruhe LIONS,1,0,1,0,71,109,-38
7,2021_22,0,Phoenix Hagen,1,1,0,2,78,63,15
8,2021_22,0,RASTA Vechta,1,0,1,0,54,68,-14
9,2021_22,0,ROSTOCK SEAWOLVES,1,1,0,2,68,54,14
10,2021_22,0,RÖMERSTROM Gladiators Trier,1,1,0,2,87,84,3
11,2021_22,0,TEAM EHINGEN URSPRING,1,0,1,0,81,98,-17
12,2021_22,0,Tigers Tübingen,1,1,0,2,83,67,16
13,2021_22,0,Uni Baskets Paderborn,1,1,0,2,98,81,17
14,2021_22,0,VfL Kirchheim Knights,1,0,1,0,67,83,-16
15,2021_22,0,VfL SparkassenStars Bochum,1,0,1,0,74,91,-17
16,2021_22,0,wiha Panthers Schwenningen,1,0,1,0,63,78,-15

In [277]:
# df3 = df_sort1 + df_sort2
df3['team'] = df_sort2['team']
df3['season'] = df_sort2['season']
df3

,season,rank,team,games_played,wins,losses,points,pts_plus,pts_minus,point_difference
0,2021_22,0,Artland Dragons,1,0,1,0,71,74,-3
1,2021_22,0,Bayer Giants Leverkusen,2,2,0,4,204,156,48
2,2021_22,0,Eisbären Bremerhaven,2,0,2,0,165,170,-5
3,2021_22,0,Itzehoe Eagles,1,1,0,2,94,78,16
4,2021_22,0,Medipolis SC Jena,2,2,0,4,179,145,34
5,2021_22,0,Nürnberg Falcons BC,2,1,1,2,145,159,-14
6,2021_22,0,PS Karlsruhe LIONS,2,1,1,2,168,179,-11
7,2021_22,0,Phoenix Hagen,2,2,0,4,161,120,41
8,2021_22,0,RASTA Vechta,2,0,2,0,111,151,-40
9,2021_22,0,ROSTOCK SEAWOLVES,2,1,1,2,153,149,4
10,2021_22,0,RÖMERSTROM Gladiators Trier,2,2,0,4,176,159,17
11,2021_22,0,TEAM EHINGEN URSPRING,2,0,2,0,159,192,-33
12,2021_22,0,Tigers Tübingen,2,1,1,2,148,144,4
13,2021_22,0,Uni Baskets Paderborn,2,1,1,2,173,170,3
14,2021_22,0,VfL Kirchheim Knights,2,0,2,0,137,180,-43
15,2021_22,0,VfL SparkassenStars Bochum,2,1,1,2,151,156,-5
16,2021_22,0,wiha Panthers Schwenningen,2,1,1,2,146,159,-13